server:
  port: 8001

spring:
  application:
    name: userinfo
  devtools:
    livereload:
      enabled: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DileepJexpert/spring-microservice-parent/tree/master/cloud-config-server





